/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AButton {
    /**
    * The classes for the button
    */
    'classes': string;
    /**
    * The value inside the button
    */
    'value': string;
  }
  interface ACard {
    'body': string;
    'date': string;
    'nickname': string;
    'username': string;
  }
  interface AGroupButton {
    'buttons': string;
  }
}

declare global {


  interface HTMLAButtonElement extends Components.AButton, HTMLStencilElement {}
  var HTMLAButtonElement: {
    prototype: HTMLAButtonElement;
    new (): HTMLAButtonElement;
  };

  interface HTMLACardElement extends Components.ACard, HTMLStencilElement {}
  var HTMLACardElement: {
    prototype: HTMLACardElement;
    new (): HTMLACardElement;
  };

  interface HTMLAGroupButtonElement extends Components.AGroupButton, HTMLStencilElement {}
  var HTMLAGroupButtonElement: {
    prototype: HTMLAGroupButtonElement;
    new (): HTMLAGroupButtonElement;
  };
  interface HTMLElementTagNameMap {
    'a-button': HTMLAButtonElement;
    'a-card': HTMLACardElement;
    'a-group-button': HTMLAGroupButtonElement;
  }
}

declare namespace LocalJSX {
  interface AButton {
    /**
    * The classes for the button
    */
    'classes'?: string;
    /**
    * The value inside the button
    */
    'value'?: string;
  }
  interface ACard {
    'body'?: string;
    'date'?: string;
    'nickname'?: string;
    'username'?: string;
  }
  interface AGroupButton {
    'buttons'?: string;
  }

  interface IntrinsicElements {
    'a-button': AButton;
    'a-card': ACard;
    'a-group-button': AGroupButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'a-button': LocalJSX.AButton & JSXBase.HTMLAttributes<HTMLAButtonElement>;
      'a-card': LocalJSX.ACard & JSXBase.HTMLAttributes<HTMLACardElement>;
      'a-group-button': LocalJSX.AGroupButton & JSXBase.HTMLAttributes<HTMLAGroupButtonElement>;
    }
  }
}


